name: build-and-push

on:
  push:
    branches: [ main ]
    paths:
      - Dockerfile
      - .github/workflows/build.yml
  workflow_dispatch:
    inputs:
      version:
        description: 'Tag to publish (e.g. v5.1, stable, cu128-py312-v5.1)'
        required: false
        default: 'v5.1'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    env:
      REGISTRY: ghcr.io
      OWNER: ready-freddy            # <-- set to your org/user (lowercase)
      IMAGE_NAME: comfyui-container  # <-- set to your package name (lowercase)

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Decide VERSION tag
        run: |
          VERSION="${{ github.event.inputs.version }}"
          if [ -z "$VERSION" ]; then VERSION="v5.1"; fi
          echo "VERSION=$VERSION" >> "$GITHUB_ENV"

      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.OWNER }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
            ${{ env.REGISTRY }}/${{ env.OWNER }}/${{ env.IMAGE_NAME }}:stable
          labels: |
            org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}
            org.opencontainers.image.revision=${{ github.sha }}
