name: Build & Push (py312 • cu128)

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Image tag to push (e.g., cu128-py312-v4 or 2025-09-20a)"
        required: true
        default: "cu128-py312-v4"
  push:
    branches: [ "feat/cu128-py312-v4-wheelbake" ]
    paths:
      - "Dockerfile"
      - "images/**/run-comfy.sh"
      - ".github/workflows/**"

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/comfyui-container
      IMAGE_TAG:  ${{ inputs.tag }}

    steps:
      - name: Check out branch
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
            ${{ env.IMAGE_NAME }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Announce
        run: |
          echo "✅ Pushed: ${IMAGE_NAME}:${IMAGE_TAG}"
          echo "Pull with: docker pull ${IMAGE_NAME}:${IMAGE_TAG}"
