name: build-comfyui-ubuntu24.04-py310

on:
  push:
    branches: [ main ]
    paths:
      - "images/comfyui-ubuntu24.04-py310/**"
      - ".github/workflows/build-comfyui-ubuntu24.04-py310.yml"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set image metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}/comfyui-ubuntu24.04-py310
          tags: |
            type=ref,event=branch
            type=sha
            type=raw,value=latest

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: images/comfyui-ubuntu24.04-py310/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=ghcr.io/${{ github.repository }}/comfyui-ubuntu24.04-py310:latest
          cache-to: type=inline
