name: build-and-push

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Docker tag to push (e.g., v5.2.5)"
        required: true
        default: "v5.2.5"

permissions:
  contents: read
  packages: write

env:
  IMAGE: ghcr.io/ready-freddy/comfyui-cu128
  CACHE: ghcr.io/ready-freddy/comfyui-cu128:cache

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: |
            ${{ env.IMAGE }}:${{ inputs.tag }}
            ${{ env.IMAGE }}:latest
          cache-from: type=registry,ref=${{ env.CACHE }}
          cache-to: type=registry,ref=${{ env.CACHE }},mode=max
