name: build-and-push
on:
  push:
    branches: [ main ]
    paths:
      - Dockerfile
      - .github/workflows/build.yml
  workflow_dispatch:
    inputs:
      version:
        description: 'Image tag (e.g., v5.2.1)'
        type: string
        required: true
        default: 'v5.2.1'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      OWNER: ${{ github.repository_owner }}
      IMAGE: comfyui-container
      VERSION: ${{ github.event.inputs.version }}
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/${{ env.OWNER }}/${{ env.IMAGE }}:${{ env.VERSION }}
            ghcr.io/${{ env.OWNER }}/${{ env.IMAGE }}:stable
          build-args: |
            IMAGE_VERSION=${{ env.VERSION }}
          labels: |
            org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.version=${{ env.VERSION }}
