name: build-and-push

on:
  # ✅ This creates the "Run workflow" button with inputs (Tag + Latest)
  workflow_dispatch:
    inputs:
      tag:
        description: "Docker tag to push (e.g., v5.2.5)"
        required: true
        type: string
      add_latest:
        description: "Also tag and push :latest?"
        required: false
        default: true
        type: boolean
  # Optional: auto-build when you push a git tag like v5.2.5
  push:
    tags:
      - "v*"

permissions:
  contents: read
  packages: write

env:
  # 🔒 Hard-code your image path so case never bites you
  IMAGE: ghcr.io/ready-freddy/comfyui-cu128
  CACHE_TAG: ghcr.io/ready-freddy/comfyui-cu128:cache

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Compute tags
        id: meta
        shell: bash
        run: |
          # Normalize owner/repo just in case (GHCR prefers lowercase)
          OWNER_LC="$(echo "${GITHUB_REPOSITORY_OWNER}" | tr '[:upper:]' '[:lower:]')"
          IMAGE="${{ env.IMAGE }}"   # already hard-coded to ghcr.io/ready-freddy/comfyui-cu128

          # Derive TAG from input or git tag event
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            TAG="${{ inputs.tag }}"
          else
            TAG="${GITHUB_REF_NAME}"   # e.g., v5.2.5 on tag push
          fi

          # Build the list of tags to push
          TAGS="${IMAGE}:${TAG}"
          if [ "${{ github.event_name }}" = "workflow_dispatch" ] && [ "${{ inputs.add_latest }}" = "true" ]; then
            TAGS="${TAGS}
${IMAGE}:latest"
          fi

          echo "image=${IMAGE}" >> "$GITHUB_OUTPUT"
          echo "tag=${TAG}" >> "$GITHUB_OUTPUT"
          printf 'tags<<EOF\n%s\nEOF\n' "$TAGS" >> "$GITHUB_OUTPUT"

          echo "Cache tag: ${{ env.CACHE_TAG }}"
          echo "Push tags:"
          echo "$TAGS"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=registry,ref=${{ env.CACHE_TAG }}
          cache-to: type=registry,ref=${{ env.CACHE_TAG }},mode=max
