name: build-and-push
on:
  push:
    branches: [ main ]
    paths:
      - Dockerfile
      - .github/workflows/build.yml
  workflow_dispatch:
    inputs:
      version:
        description: 'Tag to publish (e.g. v5.1, stable, cu128-py312-v5.1)'
        type: string
        default: 'v5.1'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      REGISTRY: ghcr.io
      OWNER: ready-freddy            # <-- set to your org/user (lowercase)
      IMAGE_NAME: comfyui-container  # <-- set to your package name (lowercase)
      VERSION: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.version || 'v5.1' }}
      IMAGE_ID: ${{ env.REGISTRY }}/${{ env.OWNER }}/${{ env.IMAGE_NAME }}
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
