name: Build & Push (CUDA 12.8 + Jupyter safe-boot)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      tag:
        description: "Image tag to publish (e.g., cu128-py312-stable.1)"
        required: true
        default: "cu128-py312-stable.1"

permissions:
  contents: read
  packages: write
  id-token: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  DEFAULT_TAG: cu128-py312-stable.1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Resolve tag
        id: tag
        run: |
          TAG_INPUT="${{ github.event.inputs.tag }}"
          if [ -n "$TAG_INPUT" ]; then TAG="$TAG_INPUT"; else TAG="${DEFAULT_TAG}"; fi
          echo "TAG=$TAG" >> "$GITHUB_OUTPUT"
          echo "Using tag: $TAG"

      # Allow comments and '# syntax=' line before FROM
      - name: Sanity: Dockerfile has a FROM somewhere sensible
        run: |
          awk '
            # skip blanks and comments
            /^[[:space:]]*$/ { next }
            /^[[:space:]]*#/  { next }
            # first significant token must be FROM
            { if ($1 != "FROM") { print "First non-comment line must start with FROM; saw: \"" $0 "\""; exit 1 } else { exit 0 } }
          ' Dockerfile

      - name: Validate entrypoint.sh (EOL + syntax)
        run: |
          test -f scripts/entrypoint.sh
          file scripts/entrypoint.sh
          if file scripts/entrypoint.sh | grep -qi 'CRLF'; then
            echo "CRLF line endings detected in scripts/entrypoint.sh"; exit 1
          fi
          bash -n scripts/entrypoint.sh

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=${{ steps.tag.outputs.TAG }}

      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.tag.outputs.TAG }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: false
          sbom: false

      - name: Summary
        run: echo "Pushed ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.tag.outputs.TAG }}"
