name: build-and-push-cu128-py312-v4

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Image tag"
        required: true
        default: "cu128-py312-v4"
  push:
    branches: [ "main" ]
    paths:
      - "Dockerfile"
      - "scripts/**"
      - "provision_all.sh"
      - ".github/workflows/build-and-push-cu128-py312-v4.yml"

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE }}:${{ github.event.inputs.tag || 'cu128-py312-v4' }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: false
          sbom: false
