name: build-and-push
on:
  push:
    branches: [ main ]
    paths:
      - Dockerfile
      - .github/workflows/build.yml
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      OWNER: ${{ github.repository_owner }}   # auto: repo owner
      IMAGE: comfyui-container               # <- change if you want (lowercase)
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/${{ env.OWNER }}/${{ env.IMAGE }}:v5.1
            ghcr.io/${{ env.OWNER }}/${{ env.IMAGE }}:stable
          labels: |
            org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}
            org.opencontainers.image.revision=${{ github.sha }}
