name: Build & Push Containers

on:
  push:
    branches: [ main ]
  workflow_dispatcH:

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write          # <-- REQUIRED for GHCR with GITHUB_TOKEN
    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: Dockerfile
            tag: cu128-py312-stable
          - dockerfile: Dockerfile.cu124
            tag: cu124-py312-stable

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      # Use the built-in GITHUB_TOKEN; no custom GHCR_TOKEN secret needed
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ matrix.tag }}
            ghcr.io/${{ github.repository }}:${{ matrix.tag }}-${{ github.sha }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache,mode=max
