name: build
on: { push: { branches: [ main ] }, workflow_dispatch: {} }
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - dockerfile: Dockerfile
            tag: cu128-py312-stable
          - dockerfile: Dockerfile.cu124
            tag: cu124-py312-stable
    steps:
      - uses: actions/checkout@v4
      - name: Login GHCR
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Build & push
        run: |
          docker build -f ${{ matrix.dockerfile }} -t ghcr.io/<org>/<repo>:${{ matrix.tag }} .
          docker push ghcr.io/<org>/<repo>:${{ matrix.tag }}
