name: build-and-push
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/comfyui-cu128:v5.2.5
          cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/comfyui-cu128:cache
          cache-to: type=registry,ref=ghcr.io/${{ github.repository_owner }}/comfyui-cu128:cache,mode=max
