name: Build & Push (py312 • cu128 • v4)

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Image tag to push (e.g., cu128-py312-v4 or 2025-09-20a)"
        required: true
        default: "cu128-py312-v4"

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/comfyui-container
      IMAGE_TAG:  ${{ inputs.tag }}
    steps:
      - name: Check out branch
        uses: actions/checkout@v4

      # Free space on GitHub runner (prevents "No space left on device")
      - name: Free disk space on runner
        uses: jlumbroso/free-disk-space@v1
        with:
          tool-cache: true
          android: true
          dotnet: true
          haskell: true
          large-packages: true
