name: ping
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: say
        run: |
          echo "ok: $GITHUB_REPOSITORY @ $GITHUB_SHA"
